### ISSUE TITLE
Meltdown on RSD processor

### ISSUE THREAD

**Issue by Hsiang0816** [rsd-devel/rsd#43]
Hi,

I am the master student from Taiwan. I'm currently studying the issue about meltdown attack. Because RSD processor is an out of order processor, I would like to ask whether this processor has any safety concerns about meltdown?

Thank you very much!

**Comment by shioyadan** [comment]
Hi, 

RSD does not have any mechanism specifically designed to protect against such attacks. However, I think that RSD in its default configuration is unlikely to be vulnerable to such attacks because it is a relatively small out-of-order processor and has low cache miss latency. If you want such attacks to work on RSD, I recommend that you experiment with some of the above parameters modified (e.g., increasing the size of the ROB and memory access latency).
